#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

struct ComputeTextureCopyParams
{
    uint Width;
    uint Height;
    uint _padding1;
    uint _padding2;
};

layout(set = 0, binding = 0) uniform Params
{
    ComputeTextureCopyParams _params;
};

layout(set = 0, binding = 1, rgba32f) uniform image2D Src;

layout(set = 0, binding = 2, rgba32f) uniform image2D Dst;

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

void CS()
{
    uvec3 id = gl_GlobalInvocationID;
    ivec2 p = ivec2(id.xy);

    vec4 color = imageLoad(Src, p);
    imageStore(Dst, p, color);
}

void main()
{
    CS();
}
