#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

struct IndirectDrawIndexedArguments
{
    uint IndexCount;
    uint InstanceCount;
    uint FirstIndex;
    int VertexOffset;
    uint FirstInstance;
};

layout(std430, set = 0, binding = 0) readonly buffer Params
{
    IndirectDrawIndexedArguments field_Params[1];
};

layout(std430, set = 0, binding = 1) buffer Destination
{
    IndirectDrawIndexedArguments field_Destination[];
};

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void CS()
{
    uvec3 id = gl_GlobalInvocationID;
    uint index = id.x;
    field_Destination[index] = field_Params[index];
}

void main()
{
    CS();
}
